### ISSUE TITLE
opening the project in 2019

### ISSUE THREAD

**Issue by taran3d** [UnityTechnologies/ShaderGraph_ExampleLibrary#9]
Cant seem to open this project in Unity 2019.1.9
everything comes up purple and I cant create a render pipeline asset, even after installing RP core, lrp and shadergraph packages

**Comment by dmalpica** [comment]
I've also found matching the project to the right Unity version and the different package versions challenging as well, especially when trying to upgrade to a new version of Unity. I've been meaning to try this myself and haven't done so, but one suggestion might be to open the project in the Unity version that works (easy if you use Unity Hub), export the scene and dependencies you need into a package, and then import that into a newer version project.

The docs say to use:

Version: Unity 2018.3.0f2
Package: com.unity.render-pipelines.lightweight: 4.6.0-preview

**Comment by dmalpica** [comment]
I tried opening the project from unity hub with 2019.1.10 and got a bunch of errors. There are some 200 instances of these two errors:

1.  ShaderGraph_ExampleLibrary_Project/Library/PackageCache/com.unity.render-pipelines.core@5.7.2/Runtime/Debugging/ProfilingSample.cs(19,16): error CS1644: Feature `null propagating operator' cannot be used because it is not part of the C# 4.0 language specification

2. ShaderGraph_ExampleLibrary_Project/Library/PackageCache/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TMPro_UGUI_Private.cs(1865,73): error CS1644: Feature `out variable declaration' cannot be used because it is not part of the C# 4.0 language specification

The approach I suggested worked but many of the materials lost bindings:

![image](https://user-images.githubusercontent.com/25854969/61418866-def7c100-a8b0-11e9-9222-14e6a51b789c.png)

**Comment by coslor** [comment]
dmalpica, just judging from the error messages, your problem could be coming from the differences between .NET 2.0 and 4.0. Have you tried changing your 2019 project to use 2.0 (Edit->Project Settings->Player->Api Compatibility Level)?

**Comment by tantorrrr** [comment]
> dmalpica, just judging from the error messages, your problem could be coming from the differences between .NET 2.0 and 4.0. Have you tried changing your 2019 project to use 2.0 (Edit->Project Settings->Player->Api Compatibility Level)?

tried, didnt work

**Comment by abhilash1910** [comment]
Did you try upgrading the project to use Version C# .NET 4.6? I think that may solve the issue.@dmalpica

**Comment by Shizola** [comment]
For anyone who see's this, this project still works fine in 2019.4.

1) remove lwrp package
2) install urp package
3) manually reassign the missing textures to the materials.
